### ISSUE TITLE
Funcionalidad del botón borrar

### ISSUE THREAD

**Issue by RbnAv** [SrRodavlas/Tienda-Videojuegos#11]
Escribir las instrucciones necesarias para que Hibernate borre el registro y sus relaciones al confirmar el dialogo de confirmación.

**Comment by SrRodavlas** [comment]
Ya se ha implementado correctamente el evento del botón. Pero necesita unas lineas mas para efectuar mediante las clases dao el borrado del registro.

**Comment by SrRodavlas** [comment]
Ya esta implementada la funcionalidad del botón borrar.
