### ISSUE TITLE
Añadir la clase Registro.

### ISSUE THREAD

**Issue by JesusFerZamo** [SrRodavlas/Tienda-Videojuegos#18]
Esta clase será la ventana para introducir los datos a la base de datos.

**Comment by SrRodavlas** [comment]
Ya esta implementado la clase Registro. Solo le falta el ActionListener de la clase Evento y podrá efectuar sus acciones. Registro esta preparado para crear 3 de los 4 posibles casos al pulsar los botones ver, nuevo y modificar de la clase Window.
