### ISSUE TITLE
Crear clase Evento

### ISSUE THREAD

**Issue by RbnAv** [SrRodavlas/Tienda-Videojuegos#19]
Implementar la clase que se encargará de la funcionalidad de los botones.

**Comment by SrRodavlas** [comment]
Reabro la tarea porque no esta terminada en absoluto. Los eventos no tienen ningún sentido porque intentan realizar acciones con las clases del paquete dao con un objeto sin inicializar (imagino que lo inicializa la clase Window al ser publico el atributo). Faltan los eventos para la clase Registro y las instrucciones dao para los otras tablas (solo esta la tabla cliente). Ademas los botones de la clase Window no dan paso directo a las clases dao. Tres de los cuatro botones deberían crear una ventana con la clase Registro y el otro botón a un dialogo de Swing. La clase Evento debería tener 2 métodos estáticos (como fue diseñado) que devolvieran los listener para las 2 clases con JFrame (Window y Registro).

**Comment by SrRodavlas** [comment]
Ya he implementado casi la totalidad de los evento para la clase Window. Queda terminar la funcionalidad del botón borrar y el método para el listener de la clase Registro.

**Comment by SrRodavlas** [comment]
Ya esta implementado la clase Evento. La interfaz ya tiene funcionalidad.
