### ISSUE TITLE
Diseño de la interfaz 

### ISSUE THREAD

**Issue by RbnAv** [SrRodavlas/Tienda-Videojuegos#3]
Diseñar la interfaz de la aplicación. 😄

**Comment by luisaoprog** [comment]
![diseno_interfaz](https://user-images.githubusercontent.com/29001841/36201801-9241befa-1181-11e8-8a20-d276c4127f07.png)
Aquí esta el boceto de la interfaz para la aplicación. Es posible que pueda haber algunos cambios posteriormente debido al trato de la relación n:m.

**Comment by SrRodavlas** [comment]
Se ha decidido cambio el label de los botones en la ventana principal por iconos.
