### ISSUE TITLE
Implementar  JFrame de Interfaz

### ISSUE THREAD

**Issue by RbnAv** [SrRodavlas/Tienda-Videojuegos#8]
Montar el frame de la  interfaz

**Comment by luisaoprog** [comment]
Implementación de la interfaz "Window" completada.
![window](https://user-images.githubusercontent.com/29001841/37010270-0fa3971a-20eb-11e8-9a73-06e2bac4a245.png)

**Comment by luisaoprog** [comment]
Implementación de la interfaz "Window" completada.
![window](https://user-images.githubusercontent.com/29001841/37010291-291c3256-20eb-11e8-806d-4a552810c693.png)
